In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

# Load Data Cancer

In [2]:
cancer = datasets.load_breast_cancer()

In [4]:
cancer.data.shape, cancer.target.shape

((569, 30), (569,))

In [6]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split (cancer.data, cancer.target, test_size=0.4, random_state=0)

In [7]:
Atribut_Training.shape

(341, 30)

In [8]:
Atribut_Testing.shape

(228, 30)

In [9]:
Kelas_Training.shape

(341,)

In [10]:
Kelas_Testing.shape

(228,)

In [11]:
modelknn = KNeighborsClassifier(n_neighbors=5)

In [12]:
modelknn.fit(Atribut_Training, Kelas_Training)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [13]:
modelknn.predict(Atribut_Testing)

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0])

In [14]:
modelknn.score(Atribut_Testing, Kelas_Testing)

0.9517543859649122

# Cross Validation cancer 5x

In [15]:
from sklearn.model_selection import cross_val_score

In [17]:
akurasi_cross_val_score = cross_val_score(modelknn, cancer.data, cancer.target, cv=5)

In [18]:
akurasi_cross_val_score

array([0.88695652, 0.93913043, 0.9380531 , 0.94690265, 0.92920354])

In [19]:
rerata_akurasi = akurasi_cross_val_score.mean()
rerata_akurasi

0.9280492497114275

# Cross Validation Cancer 10x

In [38]:
akurasi_cross_val_score = cross_val_score(modelknn, cancer.data, cancer.target, cv=10)

In [39]:
akurasi_cross_val_score

array([0.9137931 , 0.87931034, 0.89473684, 0.96491228, 0.94736842,
       0.92982456, 0.96491228, 0.92857143, 0.91071429, 0.96428571])

In [40]:
rerata_akurasi = akurasi_cross_val_score.mean()
rerata_akurasi

0.9298429262812202

# Load data wine

In [20]:
wine = datasets.load_wine()

In [21]:
wine.data.shape, wine.target.shape

((178, 13), (178,))

In [22]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split (wine.data, wine.target, test_size=0.4, random_state=0)

In [25]:
Atribut_Training.shape

(106, 13)

In [26]:
Atribut_Testing.shape

(72, 13)

In [27]:
Kelas_Training.shape

(106,)

In [28]:
Kelas_Testing.shape

(72,)

In [29]:
modelknn = KNeighborsClassifier(n_neighbors=5)

In [30]:
modelknn.fit(Atribut_Training, Kelas_Training)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [31]:
modelknn.predict(Atribut_Testing)

array([0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2,
       1, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 1,
       1, 2, 0, 2, 0, 2])

In [32]:
modelknn.score(Atribut_Testing, Kelas_Testing)

0.6666666666666666

# Cross Validation Wine 5x

In [35]:
akurasi_cross_val_score = cross_val_score(modelknn, wine.data, wine.target, cv=5)

In [36]:
akurasi_cross_val_score

array([0.7027027 , 0.66666667, 0.63888889, 0.65714286, 0.76470588])

In [37]:
rerata_akurasi = akurasi_cross_val_score.mean()
rerata_akurasi

0.6860213995508112

# Cross Validation 10x

In [41]:
akurasi_cross_val_score = cross_val_score(modelknn, wine.data, wine.target, cv=10)

In [42]:
akurasi_cross_val_score

array([0.68421053, 0.61111111, 0.66666667, 0.55555556, 0.66666667,
       0.55555556, 0.77777778, 0.66666667, 0.82352941, 0.75      ])

In [43]:
rerata_akurasi = akurasi_cross_val_score.mean()
rerata_akurasi

0.6757739938080495